import java.util.HashMap;
import java.util.Map;

public class ListaMonedas {
    private static final Map<Integer, String> codigosMoneda = new HashMap<>();

    static {
        codigosMoneda.put(1, "AED");
        codigosMoneda.put(2, "AFN");
        codigosMoneda.put(3, "ALL");
        codigosMoneda.put(4, "AMD");
        codigosMoneda.put(5, "ANG");
        codigosMoneda.put(6, "AOA");
        codigosMoneda.put(7, "ARS");
        codigosMoneda.put(8, "AUD");
        codigosMoneda.put(9, "AWG");
        codigosMoneda.put(10, "AZN");
        codigosMoneda.put(11, "BAM");
        codigosMoneda.put(12, "BBD");
        codigosMoneda.put(13, "BDT");
        codigosMoneda.put(14, "BGN");
        codigosMoneda.put(15, "BHD");
        codigosMoneda.put(16, "BIF");
        codigosMoneda.put(17, "BMD");
        codigosMoneda.put(18, "BND");
        codigosMoneda.put(19, "BOB");
        codigosMoneda.put(20, "BRL");
        codigosMoneda.put(21, "BSD");
        codigosMoneda.put(22, "BTN");
        codigosMoneda.put(23, "BWP");
        codigosMoneda.put(24, "BYN");
        codigosMoneda.put(25, "BZD");
        codigosMoneda.put(26, "CAD");
        codigosMoneda.put(27, "CDF");
        codigosMoneda.put(28, "CHF");
        codigosMoneda.put(29, "CLP");
        codigosMoneda.put(30, "CNY");
        codigosMoneda.put(31, "COP");
        codigosMoneda.put(32, "CRC");
        codigosMoneda.put(33, "CUP");
        codigosMoneda.put(34, "CVE");
        codigosMoneda.put(35, "CZK");
        codigosMoneda.put(36, "DJF");
        codigosMoneda.put(37, "DKK");
        codigosMoneda.put(38, "DOP");
        codigosMoneda.put(39, "DZD");
        codigosMoneda.put(40, "EGP");
        codigosMoneda.put(41, "ERN");
        codigosMoneda.put(42, "ETB");
        codigosMoneda.put(43, "EUR");
        codigosMoneda.put(44, "FJD");
        codigosMoneda.put(45, "FKP");
        codigosMoneda.put(46, "FOK");
        codigosMoneda.put(47, "GBP");
        codigosMoneda.put(48, "GEL");
        codigosMoneda.put(49, "GGP");
        codigosMoneda.put(50, "GHS");
        codigosMoneda.put(51, "GIP");
        codigosMoneda.put(52, "GMD");
        codigosMoneda.put(53, "GNF");
        codigosMoneda.put(54, "GTQ");
        codigosMoneda.put(55, "GYD");
        codigosMoneda.put(56, "HKD");
        codigosMoneda.put(57, "HNL");
        codigosMoneda.put(58, "HRK");
        codigosMoneda.put(59, "HTG");
        codigosMoneda.put(60, "HUF");
        codigosMoneda.put(61, "IDR");
        codigosMoneda.put(62, "ILS");
        codigosMoneda.put(63, "IMP");
        codigosMoneda.put(64, "INR");
        codigosMoneda.put(65, "IQD");
        codigosMoneda.put(66, "IRR");
        codigosMoneda.put(67, "ISK");
        codigosMoneda.put(68, "JEP");
        codigosMoneda.put(69, "JMD");
        codigosMoneda.put(70, "JOD");
        codigosMoneda.put(71, "JPY");
        codigosMoneda.put(72, "KES");
        codigosMoneda.put(73, "KGS");
        codigosMoneda.put(74, "KHR");
        codigosMoneda.put(75, "KID");
        codigosMoneda.put(76, "KMF");
        codigosMoneda.put(77, "KRW");
        codigosMoneda.put(78, "KWD");
        codigosMoneda.put(79, "KYD");
        codigosMoneda.put(80, "KZT");
        codigosMoneda.put(81, "LAK");
        codigosMoneda.put(82, "LBP");
        codigosMoneda.put(83, "LKR");
        codigosMoneda.put(84, "LRD");
        codigosMoneda.put(85, "LSL");
        codigosMoneda.put(86, "LYD");
        codigosMoneda.put(87, "MAD");
        codigosMoneda.put(88, "MDL");
        codigosMoneda.put(89, "MGA");
        codigosMoneda.put(90, "MKD");
        codigosMoneda.put(91, "MMK");
        codigosMoneda.put(92, "MNT");
        codigosMoneda.put(93, "MOP");
        codigosMoneda.put(94, "MRU");
        codigosMoneda.put(95, "MUR");
        codigosMoneda.put(96, "MVR");
        codigosMoneda.put(97, "MWK");
        codigosMoneda.put(98, "MXN");
        codigosMoneda.put(99, "MYR");
        codigosMoneda.put(100, "MZN");
        codigosMoneda.put(101, "NAD");
        codigosMoneda.put(102, "NGN");
        codigosMoneda.put(103, "NIO");
        codigosMoneda.put(104, "NOK");
        codigosMoneda.put(105, "NPR");
        codigosMoneda.put(106, "NZD");
        codigosMoneda.put(107, "OMR");
        codigosMoneda.put(108, "PAB");
        codigosMoneda.put(109, "PEN");
        codigosMoneda.put(110, "PGK");
        codigosMoneda.put(111, "PHP");
        codigosMoneda.put(112, "PKR");
        codigosMoneda.put(113, "PLN");
        codigosMoneda.put(114, "PYG");
        codigosMoneda.put(115, "QAR");
        codigosMoneda.put(116, "RON");
        codigosMoneda.put(117, "RSD");
        codigosMoneda.put(118, "RUB");
        codigosMoneda.put(119, "RWF");
        codigosMoneda.put(120, "SAR");
        codigosMoneda.put(121, "SBD");
        codigosMoneda.put(122, "SCR");
        codigosMoneda.put(123, "SDG");
        codigosMoneda.put(124, "SEK");
        codigosMoneda.put(125, "SGD");
        codigosMoneda.put(126, "SHP");
        codigosMoneda.put(127, "SLE");
        codigosMoneda.put(128, "SOS");
        codigosMoneda.put(129, "SRD");
        codigosMoneda.put(130, "SSP");
        codigosMoneda.put(131, "STN");
        codigosMoneda.put(132, "SYP");
        codigosMoneda.put(133, "SZL");
        codigosMoneda.put(134, "THB");
        codigosMoneda.put(135, "TJS");
        codigosMoneda.put(136, "TMT");
        codigosMoneda.put(137, "TND");
        codigosMoneda.put(138, "TOP");
        codigosMoneda.put(139, "TRY");
        codigosMoneda.put(140, "TTD");
        codigosMoneda.put(141, "TVD");
        codigosMoneda.put(142, "TWD");
        codigosMoneda.put(143, "TZS");
        codigosMoneda.put(144, "UAH");
        codigosMoneda.put(145, "UGX");
        codigosMoneda.put(146, "USD");
        codigosMoneda.put(147, "UYU");
        codigosMoneda.put(148, "UZS");
        codigosMoneda.put(149, "VES");
        codigosMoneda.put(150, "VND");
        codigosMoneda.put(151, "VUV");
        codigosMoneda.put(152, "WST");
        codigosMoneda.put(153, "XAF");
        codigosMoneda.put(154, "XCD");
        codigosMoneda.put(155, "XDR");
        codigosMoneda.put(156, "XOF");
        codigosMoneda.put(157, "XPF");
        codigosMoneda.put(158, "YER");
        codigosMoneda.put(159, "ZAR");
        codigosMoneda.put(160, "ZMW");
        codigosMoneda.put(161, "ZWL");
    }

    public static void mostrarListado() {
        System.out.println("Listado de códigos de moneda:");
        System.out.println("1. AED - UAE Dirham - United Arab Emirates");
        System.out.println("2. AFN - Afghan Afghani - Afghanistan");
        System.out.println("3. ALL - Albanian Lek - Albania");
        System.out.println("4. AMD - Armenian Dram - Armenia");
        System.out.println("5. ANG - Netherlands Antillian Guilder - Netherlands Antilles");
        System.out.println("6. AOA - Angolan Kwanza - Angola");
        System.out.println("7. ARS - Argentine Peso - Argentina");
        System.out.println("8. AUD - Australian Dollar - Australia");
        System.out.println("9. AWG - Aruban Florin - Aruba");
        System.out.println("10. AZN - Azerbaijani Manat - Azerbaijan");
        System.out.println("11. BAM - Bosnia and Herzegovina Mark - Bosnia and Herzegovina");
        System.out.println("12. BBD - Barbados Dollar - Barbados");
        System.out.println("13. BDT - Bangladeshi Taka - Bangladesh");
        System.out.println("14. BGN - Bulgarian Lev - Bulgaria");
        System.out.println("15. BHD - Bahraini Dinar - Bahrain");
        System.out.println("16. BIF - Burundian Franc - Burundi");
        System.out.println("17. BMD - Bermudian Dollar - Bermuda");
        System.out.println("18. BND - Brunei Dollar - Brunei");
        System.out.println("19. BOB - Bolivian Boliviano - Bolivia");
        System.out.println("20. BRL - Brazilian Real - Brazil");
        System.out.println("21. BSD - Bahamian Dollar - Bahamas");
        System.out.println("22. BTN - Bhutanese Ngultrum - Bhutan");
        System.out.println("23. BWP - Botswana Pula - Botswana");
        System.out.println("24. BYN - Belarusian Ruble - Belarus");
        System.out.println("25. BZD - Belize Dollar - Belize");
        System.out.println("26. CAD - Canadian Dollar - Canada");
        System.out.println("27. CDF - Congolese Franc - Democratic Republic of the Congo");
        System.out.println("28. CHF - Swiss Franc - Switzerland");
        System.out.println("29. CLP - Chilean Peso - Chile");
        System.out.println("30. CNY - Chinese Renminbi - China");
        System.out.println("31. COP - Colombian Peso - Colombia");
        System.out.println("32. CRC - Costa Rican Colon - Costa Rica");
        System.out.println("33. CUP - Cuban Peso - Cuba");
        System.out.println("34. CVE - Cape Verdean Escudo - Cape Verde");
        System.out.println("35. CZK - Czech Koruna - Czech Republic");
        System.out.println("36. DJF - Djiboutian Franc - Djibouti");
        System.out.println("37. DKK - Danish Krone - Denmark");
        System.out.println("38. DOP - Dominican Peso - Dominican Republic");
        System.out.println("39. DZD - Algerian Dinar - Algeria");
        System.out.println("40. EGP - Egyptian Pound - Egypt");
        System.out.println("41. ERN - Eritrean Nakfa - Eritrea");
        System.out.println("42. ETB - Ethiopian Birr - Ethiopia");
        System.out.println("43. EUR - Euro - European Union");
        System.out.println("44. FJD - Fiji Dollar - Fiji");
        System.out.println("45. FKP - Falkland Islands Pound - Falkland Islands");
        System.out.println("46. FOK - Faroese Króna - Faroe Islands");
        System.out.println("47. GBP - Pound Sterling - United Kingdom");
        System.out.println("48. GEL - Georgian Lari - Georgia");
        System.out.println("49. GGP - Guernsey Pound - Guernsey");
        System.out.println("50. GHS - Ghanaian Cedi - Ghana");
        System.out.println("51. GIP - Gibraltar Pound - Gibraltar");
        System.out.println("52. GMD - Gambian Dalasi - The Gambia");
        System.out.println("53. GNF - Guinean Franc - Guinea");
        System.out.println("54. GTQ - Guatemalan Quetzal - Guatemala");
        System.out.println("55. GYD - Guyanese Dollar - Guyana");
        System.out.println("56. HKD - Hong Kong Dollar - Hong Kong");
        System.out.println("57. HNL - Honduran Lempira - Honduras");
        System.out.println("58. HRK - Croatian Kuna - Croatia");
        System.out.println("59. HTG - Haitian Gourde - Haiti");
        System.out.println("60. HUF - Hungarian Forint - Hungary");
        System.out.println("61. IDR - Indonesian Rupiah - Indonesia");
        System.out.println("62. ILS - Israeli New Shekel - Israel");
        System.out.println("63. IMP - Manx Pound - Isle of Man");
        System.out.println("64. INR - Indian Rupee - India");
        System.out.println("65. IQD - Iraqi Dinar - Iraq");
        System.out.println("66. IRR - Iranian Rial - Iran");
        System.out.println("67. ISK - Icelandic Króna - Iceland");
        System.out.println("68. JEP - Jersey Pound - Jersey");
        System.out.println("69. JMD - Jamaican Dollar - Jamaica");
        System.out.println("70. JOD - Jordanian Dinar - Jordan");
        System.out.println("71. JPY - Japanese Yen - Japan");
        System.out.println("72. KES - Kenyan Shilling - Kenya");
        System.out.println("73. KGS - Kyrgyzstani Som - Kyrgyzstan");
        System.out.println("74. KHR - Cambodian Riel - Cambodia");
        System.out.println("75. KID - Kiribati Dollar - Kiribati");
        System.out.println("76. KMF - Comorian Franc - Comoros");
        System.out.println("77. KRW - South Korean Won - South Korea");
        System.out.println("78. KWD - Kuwaiti Dinar - Kuwait");
        System.out.println("79. KYD - Cayman Islands Dollar - Cayman Islands");
        System.out.println("80. KZT - Kazakhstani Tenge - Kazakhstan");
        System.out.println("81. LAK - Lao Kip - Laos");
        System.out.println("82. LBP - Lebanese Pound - Lebanon");
        System.out.println("83. LKR - Sri Lanka Rupee - Sri Lanka");
        System.out.println("84. LRD - Liberian Dollar - Liberia");
        System.out.println("85. LSL - Lesotho Loti - Lesotho");
        System.out.println("86. LYD - Libyan Dinar - Libya");
        System.out.println("87. MAD - Moroccan Dirham - Morocco");
        System.out.println("88. MDL - Moldovan Leu - Moldova");
        System.out.println("89. MGA - Malagasy Ariary - Madagascar");
        System.out.println("90. MKD - Macedonian Denar - North Macedonia");
        System.out.println("91. MMK - Burmese Kyat - Myanmar");
        System.out.println("92. MNT - Mongolian Tögrög - Mongolia");
        System.out.println("93. MOP - Macanese Pataca - Macau");
        System.out.println("94. MRU - Mauritanian Ouguiya - Mauritania");
        System.out.println("95. MUR - Mauritian Rupee - Mauritius");
        System.out.println("96. MVR - Maldivian Rufiyaa - Maldives");
        System.out.println("97. MWK - Malawian Kwacha - Malawi");
        System.out.println("98. MXN - Mexican Peso - Mexico");
        System.out.println("99. MYR - Malaysian Ringgit - Malaysia");
        System.out.println("100. MZN - Mozambican Metical - Mozambique");
        System.out.println("101. NAD - Namibian Dollar - Namibia");
        System.out.println("102. NGN - Nigerian Naira - Nigeria");
        System.out.println("103. NIO - Nicaraguan Córdoba - Nicaragua");
        System.out.println("104. NOK - Norwegian Krone - Norway");
        System.out.println("105. NPR - Nepalese Rupee - Nepal");
        System.out.println("106. NZD - New Zealand Dollar - New Zealand");
        System.out.println("107. OMR - Omani Rial - Oman");
        System.out.println("108. PAB - Panamanian Balboa - Panama");
        System.out.println("109. PEN - Peruvian Sol - Peru");
        System.out.println("110. PGK - Papua New Guinean Kina - Papua New Guinea");
        System.out.println("111. PHP - Philippine Peso - Philippines");
        System.out.println("112. PKR - Pakistani Rupee - Pakistan");
        System.out.println("113. PLN - Polish Złoty - Poland");
        System.out.println("114. PYG - Paraguayan Guaraní - Paraguay");
        System.out.println("115. QAR - Qatari Riyal - Qatar");
        System.out.println("116. RON - Romanian Leu - Romania");
        System.out.println("117. RSD - Serbian Dinar - Serbia");
        System.out.println("118. RUB - Russian Ruble - Russia");
        System.out.println("119. RWF - Rwandan Franc - Rwanda");
        System.out.println("120. SAR - Saudi Riyal - Saudi Arabia");
        System.out.println("121. SBD - Solomon Islands Dollar - Solomon Islands");
        System.out.println("122. SCR - Seychellois Rupee - Seychelles");
        System.out.println("123. SDG - Sudanese Pound - Sudan");
        System.out.println("124. SEK - Swedish Krona - Sweden");
        System.out.println("125. SGD - Singapore Dollar - Singapore");
        System.out.println("126. SHP - Saint Helena Pound - Saint Helena");
        System.out.println("127. SLE - Sierra Leonean Leone - Sierra Leone");
        System.out.println("128. SOS - Somali Shilling - Somalia");
        System.out.println("129. SRD - Surinamese Dollar - Suriname");
        System.out.println("130. SSP - South Sudanese Pound - South Sudan");
        System.out.println("131. STN - São Tomé and Príncipe Dobra - São Tomé and Príncipe");
        System.out.println("132. SYP - Syrian Pound - Syria");
        System.out.println("133. SZL - Eswatini Lilangeni - Eswatini");
        System.out.println("134. THB - Thai Baht - Thailand");
        System.out.println("135. TJS - Tajikistani Somoni - Tajikistan");
        System.out.println("136. TMT - Turkmenistan Manat - Turkmenistan");
        System.out.println("137. TND - Tunisian Dinar - Tunisia");
        System.out.println("138. TOP - Tongan Paʻanga - Tonga");
        System.out.println("139. TRY - Turkish Lira - Turkey");
        System.out.println("140. TTD - Trinidad and Tobago Dollar - Trinidad and Tobago");
        System.out.println("141. TVD - Tuvaluan Dollar - Tuvalu");
        System.out.println("142. TWD - New Taiwan Dollar - Taiwan");
        System.out.println("143. TZS - Tanzanian Shilling - Tanzania");
        System.out.println("144. UAH - Ukrainian Hryvnia - Ukraine");
        System.out.println("145. UGX - Ugandan Shilling - Uganda");
        System.out.println("146. USD - United States Dollar - United States");
        System.out.println("147. UYU - Uruguayan Peso - Uruguay");
        System.out.println("148. UZS - Uzbekistani So'm - Uzbekistan");
        System.out.println("149. VES - Venezuelan Bolívar Soberano - Venezuela");
        System.out.println("150. VND - Vietnamese Đồng - Vietnam");
        System.out.println("151. VUV - Vanuatu Vatu - Vanuatu");
        System.out.println("152. WST - Samoan Tālā - Samoa");
        System.out.println("153. XAF - Central African CFA Franc - CEMAC");
        System.out.println("154. XCD - East Caribbean Dollar - Organisation of Eastern Caribbean States");
        System.out.println("155. XDR - Special Drawing Rights - International Monetary Fund");
        System.out.println("156. XOF - West African CFA franc - CFA");
        System.out.println("157. XPF - CFP Franc - Collectivités d'Outre-Mer");
        System.out.println("158. YER - Yemeni Rial - Yemen");
        System.out.println("159. ZAR - South African Rand - South Africa");
        System.out.println("160. ZMW - Zambian Kwacha - Zambia");
        System.out.println("161. ZWL - Zimbabwean Dollar - Zimbabwe");
    }
    public static String getCodigoMoneda(int opcion) {
        return codigosMoneda.get(opcion);
    }
}

